/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HackathonRouteImport } from './routes/hackathon'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as CantonVsEvmRouteImport } from './routes/canton-vs-evm'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AllocationsRouteImport } from './routes/allocations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrustTrustIdRouteImport } from './routes/trust.$trustId'
import { Route as IcbIcbCodeRouteImport } from './routes/icb.$icbCode'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicAdminSmokeInvoiceRouteImport } from './routes/api/public/admin.smoke-invoice'
import { Route as ApiPublicAdminSelfDiagnoseRouteImport } from './routes/api/public/admin.self-diagnose'
import { Route as ApiPublicAdminSelfDeployRouteImport } from './routes/api/public/admin.self-deploy'
import { Route as ApiPublicAdminMintMockUsdcxRouteImport } from './routes/api/public/admin.mint-mock-usdcx'
import { Route as ApiPublicAdminListPartiesProbeRouteImport } from './routes/api/public/admin.list-parties-probe'
import { Route as ApiPublicAdminDiagnoseRouteImport } from './routes/api/public/admin.diagnose'
import { Route as ApiPublicAdminDeployTraceRouteImport } from './routes/api/public/admin.deploy-trace'
import { Route as ApiPublicAdminDeployRouteImport } from './routes/api/public/admin.deploy'

const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonRoute = HackathonRouteImport.update({
  id: '/hackathon',
  path: '/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const CantonVsEvmRoute = CantonVsEvmRouteImport.update({
  id: '/canton-vs-evm',
  path: '/canton-vs-evm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsRoute = AllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustTrustIdRoute = TrustTrustIdRouteImport.update({
  id: '/trust/$trustId',
  path: '/trust/$trustId',
  getParentRoute: () => rootRouteImport,
} as any)
const IcbIcbCodeRoute = IcbIcbCodeRouteImport.update({
  id: '/icb/$icbCode',
  path: '/icb/$icbCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSmokeInvoiceRoute =
  ApiPublicAdminSmokeInvoiceRouteImport.update({
    id: '/api/public/admin/smoke-invoice',
    path: '/api/public/admin/smoke-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSelfDiagnoseRoute =
  ApiPublicAdminSelfDiagnoseRouteImport.update({
    id: '/api/public/admin/self-diagnose',
    path: '/api/public/admin/self-diagnose',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSelfDeployRoute =
  ApiPublicAdminSelfDeployRouteImport.update({
    id: '/api/public/admin/self-deploy',
    path: '/api/public/admin/self-deploy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminMintMockUsdcxRoute =
  ApiPublicAdminMintMockUsdcxRouteImport.update({
    id: '/api/public/admin/mint-mock-usdcx',
    path: '/api/public/admin/mint-mock-usdcx',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminListPartiesProbeRoute =
  ApiPublicAdminListPartiesProbeRouteImport.update({
    id: '/api/public/admin/list-parties-probe',
    path: '/api/public/admin/list-parties-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminDiagnoseRoute = ApiPublicAdminDiagnoseRouteImport.update({
  id: '/api/public/admin/diagnose',
  path: '/api/public/admin/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeployTraceRoute =
  ApiPublicAdminDeployTraceRouteImport.update({
    id: '/api/public/admin/deploy-trace',
    path: '/api/public/admin/deploy-trace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminDeployRoute = ApiPublicAdminDeployRouteImport.update({
  id: '/api/public/admin/deploy',
  path: '/api/public/admin/deploy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/canton-vs-evm': typeof CantonVsEvmRoute
  '/deck': typeof DeckRoute
  '/deploy': typeof DeployRoute
  '/hackathon': typeof HackathonRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ledger': typeof LedgerRoute
  '/contracts/new': typeof ContractsNewRoute
  '/icb/$icbCode': typeof IcbIcbCodeRoute
  '/trust/$trustId': typeof TrustTrustIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/admin/deploy': typeof ApiPublicAdminDeployRoute
  '/api/public/admin/deploy-trace': typeof ApiPublicAdminDeployTraceRoute
  '/api/public/admin/diagnose': typeof ApiPublicAdminDiagnoseRoute
  '/api/public/admin/list-parties-probe': typeof ApiPublicAdminListPartiesProbeRoute
  '/api/public/admin/mint-mock-usdcx': typeof ApiPublicAdminMintMockUsdcxRoute
  '/api/public/admin/self-deploy': typeof ApiPublicAdminSelfDeployRoute
  '/api/public/admin/self-diagnose': typeof ApiPublicAdminSelfDiagnoseRoute
  '/api/public/admin/smoke-invoice': typeof ApiPublicAdminSmokeInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/canton-vs-evm': typeof CantonVsEvmRoute
  '/deck': typeof DeckRoute
  '/deploy': typeof DeployRoute
  '/hackathon': typeof HackathonRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ledger': typeof LedgerRoute
  '/contracts/new': typeof ContractsNewRoute
  '/icb/$icbCode': typeof IcbIcbCodeRoute
  '/trust/$trustId': typeof TrustTrustIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/admin/deploy': typeof ApiPublicAdminDeployRoute
  '/api/public/admin/deploy-trace': typeof ApiPublicAdminDeployTraceRoute
  '/api/public/admin/diagnose': typeof ApiPublicAdminDiagnoseRoute
  '/api/public/admin/list-parties-probe': typeof ApiPublicAdminListPartiesProbeRoute
  '/api/public/admin/mint-mock-usdcx': typeof ApiPublicAdminMintMockUsdcxRoute
  '/api/public/admin/self-deploy': typeof ApiPublicAdminSelfDeployRoute
  '/api/public/admin/self-diagnose': typeof ApiPublicAdminSelfDiagnoseRoute
  '/api/public/admin/smoke-invoice': typeof ApiPublicAdminSmokeInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/canton-vs-evm': typeof CantonVsEvmRoute
  '/deck': typeof DeckRoute
  '/deploy': typeof DeployRoute
  '/hackathon': typeof HackathonRoute
  '/how-it-works': typeof HowItWorksRoute
  '/ledger': typeof LedgerRoute
  '/contracts/new': typeof ContractsNewRoute
  '/icb/$icbCode': typeof IcbIcbCodeRoute
  '/trust/$trustId': typeof TrustTrustIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/admin/deploy': typeof ApiPublicAdminDeployRoute
  '/api/public/admin/deploy-trace': typeof ApiPublicAdminDeployTraceRoute
  '/api/public/admin/diagnose': typeof ApiPublicAdminDiagnoseRoute
  '/api/public/admin/list-parties-probe': typeof ApiPublicAdminListPartiesProbeRoute
  '/api/public/admin/mint-mock-usdcx': typeof ApiPublicAdminMintMockUsdcxRoute
  '/api/public/admin/self-deploy': typeof ApiPublicAdminSelfDeployRoute
  '/api/public/admin/self-diagnose': typeof ApiPublicAdminSelfDiagnoseRoute
  '/api/public/admin/smoke-invoice': typeof ApiPublicAdminSmokeInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocations'
    | '/audit'
    | '/auth'
    | '/canton-vs-evm'
    | '/deck'
    | '/deploy'
    | '/hackathon'
    | '/how-it-works'
    | '/ledger'
    | '/contracts/new'
    | '/icb/$icbCode'
    | '/trust/$trustId'
    | '/api/public/health'
    | '/api/public/admin/deploy'
    | '/api/public/admin/deploy-trace'
    | '/api/public/admin/diagnose'
    | '/api/public/admin/list-parties-probe'
    | '/api/public/admin/mint-mock-usdcx'
    | '/api/public/admin/self-deploy'
    | '/api/public/admin/self-diagnose'
    | '/api/public/admin/smoke-invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocations'
    | '/audit'
    | '/auth'
    | '/canton-vs-evm'
    | '/deck'
    | '/deploy'
    | '/hackathon'
    | '/how-it-works'
    | '/ledger'
    | '/contracts/new'
    | '/icb/$icbCode'
    | '/trust/$trustId'
    | '/api/public/health'
    | '/api/public/admin/deploy'
    | '/api/public/admin/deploy-trace'
    | '/api/public/admin/diagnose'
    | '/api/public/admin/list-parties-probe'
    | '/api/public/admin/mint-mock-usdcx'
    | '/api/public/admin/self-deploy'
    | '/api/public/admin/self-diagnose'
    | '/api/public/admin/smoke-invoice'
  id:
    | '__root__'
    | '/'
    | '/allocations'
    | '/audit'
    | '/auth'
    | '/canton-vs-evm'
    | '/deck'
    | '/deploy'
    | '/hackathon'
    | '/how-it-works'
    | '/ledger'
    | '/contracts/new'
    | '/icb/$icbCode'
    | '/trust/$trustId'
    | '/api/public/health'
    | '/api/public/admin/deploy'
    | '/api/public/admin/deploy-trace'
    | '/api/public/admin/diagnose'
    | '/api/public/admin/list-parties-probe'
    | '/api/public/admin/mint-mock-usdcx'
    | '/api/public/admin/self-deploy'
    | '/api/public/admin/self-diagnose'
    | '/api/public/admin/smoke-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationsRoute: typeof AllocationsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CantonVsEvmRoute: typeof CantonVsEvmRoute
  DeckRoute: typeof DeckRoute
  DeployRoute: typeof DeployRoute
  HackathonRoute: typeof HackathonRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LedgerRoute: typeof LedgerRoute
  ContractsNewRoute: typeof ContractsNewRoute
  IcbIcbCodeRoute: typeof IcbIcbCodeRoute
  TrustTrustIdRoute: typeof TrustTrustIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicAdminDeployRoute: typeof ApiPublicAdminDeployRoute
  ApiPublicAdminDeployTraceRoute: typeof ApiPublicAdminDeployTraceRoute
  ApiPublicAdminDiagnoseRoute: typeof ApiPublicAdminDiagnoseRoute
  ApiPublicAdminListPartiesProbeRoute: typeof ApiPublicAdminListPartiesProbeRoute
  ApiPublicAdminMintMockUsdcxRoute: typeof ApiPublicAdminMintMockUsdcxRoute
  ApiPublicAdminSelfDeployRoute: typeof ApiPublicAdminSelfDeployRoute
  ApiPublicAdminSelfDiagnoseRoute: typeof ApiPublicAdminSelfDiagnoseRoute
  ApiPublicAdminSmokeInvoiceRoute: typeof ApiPublicAdminSmokeInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon': {
      id: '/hackathon'
      path: '/hackathon'
      fullPath: '/hackathon'
      preLoaderRoute: typeof HackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canton-vs-evm': {
      id: '/canton-vs-evm'
      path: '/canton-vs-evm'
      fullPath: '/canton-vs-evm'
      preLoaderRoute: typeof CantonVsEvmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations': {
      id: '/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/$trustId': {
      id: '/trust/$trustId'
      path: '/trust/$trustId'
      fullPath: '/trust/$trustId'
      preLoaderRoute: typeof TrustTrustIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icb/$icbCode': {
      id: '/icb/$icbCode'
      path: '/icb/$icbCode'
      fullPath: '/icb/$icbCode'
      preLoaderRoute: typeof IcbIcbCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/smoke-invoice': {
      id: '/api/public/admin/smoke-invoice'
      path: '/api/public/admin/smoke-invoice'
      fullPath: '/api/public/admin/smoke-invoice'
      preLoaderRoute: typeof ApiPublicAdminSmokeInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/self-diagnose': {
      id: '/api/public/admin/self-diagnose'
      path: '/api/public/admin/self-diagnose'
      fullPath: '/api/public/admin/self-diagnose'
      preLoaderRoute: typeof ApiPublicAdminSelfDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/self-deploy': {
      id: '/api/public/admin/self-deploy'
      path: '/api/public/admin/self-deploy'
      fullPath: '/api/public/admin/self-deploy'
      preLoaderRoute: typeof ApiPublicAdminSelfDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/mint-mock-usdcx': {
      id: '/api/public/admin/mint-mock-usdcx'
      path: '/api/public/admin/mint-mock-usdcx'
      fullPath: '/api/public/admin/mint-mock-usdcx'
      preLoaderRoute: typeof ApiPublicAdminMintMockUsdcxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/list-parties-probe': {
      id: '/api/public/admin/list-parties-probe'
      path: '/api/public/admin/list-parties-probe'
      fullPath: '/api/public/admin/list-parties-probe'
      preLoaderRoute: typeof ApiPublicAdminListPartiesProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/diagnose': {
      id: '/api/public/admin/diagnose'
      path: '/api/public/admin/diagnose'
      fullPath: '/api/public/admin/diagnose'
      preLoaderRoute: typeof ApiPublicAdminDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/deploy-trace': {
      id: '/api/public/admin/deploy-trace'
      path: '/api/public/admin/deploy-trace'
      fullPath: '/api/public/admin/deploy-trace'
      preLoaderRoute: typeof ApiPublicAdminDeployTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/deploy': {
      id: '/api/public/admin/deploy'
      path: '/api/public/admin/deploy'
      fullPath: '/api/public/admin/deploy'
      preLoaderRoute: typeof ApiPublicAdminDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationsRoute: AllocationsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CantonVsEvmRoute: CantonVsEvmRoute,
  DeckRoute: DeckRoute,
  DeployRoute: DeployRoute,
  HackathonRoute: HackathonRoute,
  HowItWorksRoute: HowItWorksRoute,
  LedgerRoute: LedgerRoute,
  ContractsNewRoute: ContractsNewRoute,
  IcbIcbCodeRoute: IcbIcbCodeRoute,
  TrustTrustIdRoute: TrustTrustIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicAdminDeployRoute: ApiPublicAdminDeployRoute,
  ApiPublicAdminDeployTraceRoute: ApiPublicAdminDeployTraceRoute,
  ApiPublicAdminDiagnoseRoute: ApiPublicAdminDiagnoseRoute,
  ApiPublicAdminListPartiesProbeRoute: ApiPublicAdminListPartiesProbeRoute,
  ApiPublicAdminMintMockUsdcxRoute: ApiPublicAdminMintMockUsdcxRoute,
  ApiPublicAdminSelfDeployRoute: ApiPublicAdminSelfDeployRoute,
  ApiPublicAdminSelfDiagnoseRoute: ApiPublicAdminSelfDiagnoseRoute,
  ApiPublicAdminSmokeInvoiceRoute: ApiPublicAdminSmokeInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
